spring:
  application:
    name: chatbot
  jackson:
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  profiles:
    active: dev

server:
  port: 8888

plugins:
  functions:
    - å¸®åŠ©â“ï¼šæŸ¥çœ‹åŠŸèƒ½åˆ—è¡¨ã€‚
    - ç§¯åˆ†ğŸ’°ï¼šæŸ¥çœ‹ç§¯åˆ†ï¼Œç§¯åˆ†å¯ä»¥åœ¨å…¶ä»–åŠŸèƒ½ä¸­ä½¿ç”¨ã€‚
    - ç­¾åˆ°ğŸ“Œï¼šæ¯å¤©å¯ç­¾åˆ°ä¸€æ¬¡ï¼Œè·å–ç§¯åˆ†ã€‚

